### ISSUE TITLE
Markdown syntax

### ISSUE THREAD

**Issue by james2doyle** [jasonlong/lavalamp#11]
I was playing around with highlighting Markdown. I am really unsure about what color to pick. So I ended up using a bunch of colors. This is sort of a recreation of a sublime markdown theme that I use.

![screen shot 2014-07-12 at 1 01 06 pm](https://cloud.githubusercontent.com/assets/1425304/3562232/26700106-09e6-11e4-8e7d-72ec109e4a4f.png)
![screen shot 2014-07-12 at 12 56 52 pm](https://cloud.githubusercontent.com/assets/1425304/3562218/99f98026-09e5-11e4-8862-b0271c069da1.png)
![screen shot 2014-07-12 at 12 56 59 pm](https://cloud.githubusercontent.com/assets/1425304/3562219/9a013b72-09e5-11e4-8c77-02944d35b73b.png)

As you can see, I am having problems getting the matching HTML end tag to highlight so I am still working on that.

Any feedback?

**Comment by jasonlong** [comment]
Closing as stale for now. Feel free to reopen.
