### ISSUE TITLE
Implement: support for alternate markdown syntax groups

### ISSUE THREAD

**Issue by romgrk** [jasonlong/lavalamp#15]
Some markdown plugins use `mkd*` prefix instead of  `markdown*`.
Maybe some automation could help. Maybe some help could help. Is your development environment public?

Oh, I realize I´ve been assuming `vim` the whole time. This is for the `vim` part.

This look nice. Well the screenshots. Couldn't get it going, but I'd love to. (Is this still a WIP?)

**Comment by jasonlong** [comment]
For Markdown, I use https://github.com/plasticboy/vim-markdown and the rules in this theme assume that. I'm not going to go through all the other MD plugins to add their names, but anyone else is welcome to add them.

And yeah, this is definitely a WIP but it's very customized to my preferences. It isn't for everyone.

**Comment by jasonlong** [comment]
Oh, as for dev environment, there are some things (including my vimrc) over at https://github.com/jasonlong/dotfiles

**Comment by romgrk** [comment]
Ok, thanks! The whole language-by-color renders very well, nice idea.
